import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Sidebar from "./components/sidebar";
import Providers from "./provider/page";
import AudioPlayer from "./components/player";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="h-screen md:h-screen flex flex-col bg-gray-900 space-y-1 pb-24 md:pb-0">
        <Providers>
          <Header />

          <div className="flex-1 flex min-h-0">
            <Sidebar />
            <div className="w-full overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
              {" "}
              {children}
            </div>
          </div>
          <div>
            <AudioPlayer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
